INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (1,"unpaid"),
  (2,"Paid"),
  (3,"unpaid"),
  (4,"Paid"),
  (5,"unpaid"),
  (6,"Paid"),
  (7,"Paid"),
  (8,"unpaid"),
  (9,"Paid"),
  (10,"Paid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (11,"unpaid"),
  (12,"Paid"),
  (13,"unpaid"),
  (14,"unpaid"),
  (15,"Paid"),
  (16,"Paid"),
  (17,"unpaid"),
  (18,"unpaid"),
  (19,"unpaid"),
  (20,"Paid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (21,"unpaid"),
  (22,"Paid"),
  (23,"unpaid"),
  (24,"unpaid"),
  (25,"unpaid"),
  (26,"Paid"),
  (27,"unpaid"),
  (28,"Paid"),
  (29,"Paid"),
  (30,"unpaid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (31,"unpaid"),
  (32,"Paid"),
  (33,"unpaid"),
  (34,"unpaid"),
  (35,"unpaid"),
  (36,"unpaid"),
  (37,"Paid"),
  (38,"Paid"),
  (39,"Paid"),
  (40,"Paid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (41,"Paid"),
  (42,"Paid"),
  (43,"Paid"),
  (44,"Paid"),
  (45,"Paid"),
  (46,"unpaid"),
  (47,"unpaid"),
  (48,"Paid"),
  (49,"Paid"),
  (50,"Paid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (51,"Paid"),
  (52,"Paid"),
  (53,"Paid"),
  (54,"unpaid"),
  (55,"unpaid"),
  (56,"Paid"),
  (57,"Paid"),
  (58,"unpaid"),
  (59,"unpaid"),
  (60,"unpaid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (61,"Paid"),
  (62,"Paid"),
  (63,"unpaid"),
  (64,"unpaid"),
  (65,"Paid"),
  (66,"Paid"),
  (67,"unpaid"),
  (68,"unpaid"),
  (69,"unpaid"),
  (70,"Paid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (71,"unpaid"),
  (72,"Paid"),
  (73,"unpaid"),
  (74,"Paid"),
  (75,"unpaid"),
  (76,"unpaid"),
  (77,"unpaid"),
  (78,"unpaid"),
  (79,"Paid"),
  (80,"unpaid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (81,"Paid"),
  (82,"unpaid"),
  (83,"unpaid"),
  (84,"Paid"),
  (85,"Paid"),
  (86,"unpaid"),
  (87,"Paid"),
  (88,"unpaid"),
  (89,"Paid"),
  (90,"unpaid");
INSERT INTO Invoice_status (InvoiceID,Status)
VALUES
  (91,"Paid"),
  (92,"unpaid"),
  (93,"unpaid"),
  (94,"unpaid"),
  (95,"Paid"),
  (96,"unpaid"),
  (97,"unpaid"),
  (98,"unpaid"),
  (99,"unpaid"),
  (100,"unpaid");
